[package]
name = "cosyne"
version = "0.0.1"
authors = ["Mladen Brankovic <root@brankovic.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
