version: '3'

services:
  cosyne:
    image: 'cosyne'
    build: '.'
    hostname: 'cosyne'
    container_name: 'cosyne'
    restart: 'unless-stopped'
    environment:
      APPLICATION_ID: '${APPLICATION_ID:?}'
      DISCORD_TOKEN: '${DISCORD_TOKEN:?}'
      LOG_LEVEL: '${LOG_LEVEL:-WARNING}'
